### ISSUE TITLE
Where can I find the paper

### ISSUE THREAD

**Issue by AGTSAAA** [syr-cn/SimSGT#2]
Dear author

Thank you very much for your great work!

I want to ask where I can find you paper or your preprint?

My email is [704767085@qq.com](mailto:704767085@qq.com). Could you please send the paper via my email? I will only read it  only for academic study.

**Comment by acharkq** [comment]
Hi 

Thanks for your interest. The pre-print is now available at https://arxiv.org/abs/2310.14753.
