### ISSUE TITLE
Pretrained Checkpoints?

### ISSUE THREAD

**Issue by hxu105** [syr-cn/SimSGT#9]
Hi, thank you for sharing this amazing work. I am wondering if there is any plan for releasing the pre-trained checkpoints. If so, when shall we expect to have those checkpoints published?

Many thanks

**Comment by syr-cn** [comment]
Thanks for your interest. I'm sorry but there's no plan for releasing our pre-trained checkpoints. You may follow the instructions in this repo to pre-trained from scratch.
